DynamoDB CDK for Archive Parts Table
aws-solutions/amazon-s3-glacier-refreezer pull request #103
Opened 2023-03-23 18:58 UTC by dbb-aws-only

https://app.asana.com/0/1202938635037719/1203922468885149/f

Changed one integration test as well to fix a timeout error in the test (I increased the timeout limit)

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2023-03-23 20:13 UTC, bassemwanis reviewed
Once confirming the final schema, we will need unit and integration tests.

2023-03-23 20:13 UTC, bassemwanis commented on source/refreezer/infrastructure/stack.py
> +            "ArchivePartsTable",
If we will use this table for Inventory tracking as well, should we have a more generic name?

2023-03-23 20:13 UTC, bassemwanis commented on source/refreezer/infrastructure/stack.py
> +            stream=dynamodb.StreamViewType.NEW_AND_OLD_IMAGES,
Do we need stream for this table?

2023-03-24 12:26 UTC, dbb-aws-only commented on source/refreezer/infrastructure/stack.py
> +            "ArchivePartsTable",
Agreed - let's change it once we understand what the final schema for archive will be and what we need for Inventory.

2023-03-24 12:31 UTC, dbb-aws-only commented on source/refreezer/infrastructure/stack.py
> +            stream=dynamodb.StreamViewType.NEW_AND_OLD_IMAGES,
Nope - good call.  We'll let the Lambda pull once the job is complete.   It's been removed.

2023-03-27 16:30 UTC, kamyarz-aws commented
I think you need to add a test to test_stack.py to check if table is created in cdk template

2023-03-27 22:15 UTC, dbb-aws-only commented
> I think you need to add a test to test_stack.py to check if table is created in cdk template

The table only shows up when you attach it to a Lambda.  I'll update the tests once the table is in use.

2023-03-29 21:40 UTC, schana requested changes
The commits shouldn't include the merge commit. Please clean this up as well.

2023-03-29 21:40 UTC, schana commented on source/refreezer/infrastructure/stack.py
> +            point_in_time_recovery=True,
Why is this enabled?

2023-03-29 21:40 UTC, schana commented on source/refreezer/infrastructure/stack.py
> +        archive_retrieval_table = dynamodb.Table(
This needs tested.

2023-03-29 23:41 UTC, dbb-aws-only commented
Closed in error

2023-03-29 23:52 UTC, dbb-aws-only commented on source/refreezer/infrastructure/stack.py
> +    ARCHIVE_RETRIEVAL_TABLE_NAME = "ARTN"
Done.  I also renamed the variable to reflect the fact that we're also storing Inventory in addition to Archive data.

2023-03-29 23:52 UTC, dbb-aws-only commented on source/refreezer/infrastructure/stack.py
> +            "GlacierArchiveRetrieval",
Renamed.

2023-03-29 23:52 UTC, dbb-aws-only commented on source/refreezer/infrastructure/stack.py
> +            point_in_time_recovery=True,
Removed.

2023-03-30 14:15 UTC, dbb-aws-only commented on source/refreezer/infrastructure/stack.py
> +            point_in_time_recovery=True,
Actually - there's a CDK nag saying that the Point In Time is more insurance...

`The DynamoDB table does not have Point-in-time Recovery enabled. DynamoDB continuous backups represent an additional layer of insurance against accidental loss of data on top of on-demand backups. The DynamoDB service can back up the data with per-second granularity and restore it to any single second from the time PITR was enabled up to the prior 35 days.\n`

2023-03-30 14:16 UTC, dbb-aws-only commented
> The commits shouldn't include the merge commit. Please clean this up as well.

Done

2023-03-30 14:39 UTC, schana commented on source/refreezer/infrastructure/stack.py
> +            point_in_time_recovery=True,
This is a cost consideration. We should leave it disabled and suppress the cdk nag, and add a task to the backlog to address later.

2023-03-30 14:42 UTC, dbb-aws-only commented on source/refreezer/infrastructure/stack.py
> +            point_in_time_recovery=True,
Ok - I'll add the Nag Suppression code.  I'll add an Asana Task, too.

2023-03-30 16:28 UTC, kamyarz-aws approved these changes

2023-03-31 19:28 UTC, bassemwanis commented on source/refreezer/pipeline/stack.py
> +                            f"arn:aws:dynamodb:{Aws.REGION}:{Aws.ACCOUNT_ID}:table/"
Can you re-use same PolicyStatement of `AsyncFacilitatorTable` and add `GlacierObjectRetrieval` table to the resources array?

2023-04-01 15:46 UTC, dbb-aws-only commented on source/refreezer/pipeline/stack.py
> +                            f"arn:aws:dynamodb:{Aws.REGION}:{Aws.ACCOUNT_ID}:table/"
Done.

2023-04-01 15:48 UTC, dbb-aws-only commented
> Once confirming the final schema, we will need unit and integration tests.

They are both added now - Simon and I are making very minor changes to the schema as we go, but the bulk of the I/O is well understood now.  There are both Unit and Integration tests in this PR now.

2023-04-03 14:30 UTC, bassemwanis approved these changes

2023-04-03 15:22 UTC, merged