Initiate Workflow PutItem
aws-solutions/amazon-s3-glacier-refreezer pull request #115
Opened 2023-04-01 16:03 UTC by dbb-aws-only

*Issue #, if available:*
https://app.asana.com/0/1202938635037719/1204196022036762/f

*Description of changes:*
Initiate the workflow and store the JobID and ArchiveID to the DynamoDB table

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2023-04-05 15:31 UTC, kamyarz-aws requested changes
Please do git pull rebase locally, my code changes are showing in your branch and there are 3 commits.

2023-04-05 15:39 UTC, dbb-aws-only commented
> Please do git pull rebase locally, my code changes are showing in your branch and there are 3 commits.

Done.

2023-04-06 14:31 UTC, kamyarz-aws approved these changes

2023-04-06 14:49 UTC, simonkrol approved these changes

2023-04-06 14:50 UTC, merged

2023-04-06 19:22 UTC, bassemwanis commented on source/refreezer/infrastructure/stack.py
> +        initiate_retrieval_dynamo_db_put = sfn.CustomState(
There is an optimized DynamoDB PutItem state instead of using  step function SDK integration using custom state

2023-04-06 19:22 UTC, bassemwanis commented on source/refreezer/infrastructure/stack.py
> +                        "S": "meta",
`S.$` instead of `S`

2023-04-06 19:22 UTC, bassemwanis commented on source/refreezer/infrastructure/stack.py
> +                        "S": "$$.Execution.StartTime",
`S.$` instead of `S`

2023-04-06 19:22 UTC, bassemwanis commented on source/refreezer/infrastructure/stack.py
> +                        "S": "$.JobId",
`S.$` instead of `S`

2023-04-06 19:22 UTC, bassemwanis commented on source/refreezer/infrastructure/stack.py
> +                        "S": "IR:$.ArchiveId",
`"S.$": "States.Format('IR:{}', $.ArchiveId)"`
https://docs.aws.amazon.com/step-functions/latest/dg/amazon-states-language-intrinsic-functions.html

2023-04-06 19:22 UTC, bassemwanis commented on source/tests/integration/infrastructure/test_initiate_retrieval_step_function.py
> +    sf_history_output = client.get_execution_history(
Split this test into a new test. `test_state_machine_start_execution` is only testing that the step function is executable.