Fix 115 workflow put item
aws-solutions/amazon-s3-glacier-refreezer pull request #126
Opened 2023-04-09 21:46 UTC by dbb-aws-only

*Issue #, if available:*

*Description of changes:*
Change the step function from custom to dynamodb specific function

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2023-04-14 13:42 UTC, kamyarz-aws commented on source/refreezer/infrastructure/stack.py
>              },
```
ddb_input_map = {
    "pk": "$.ArchiveId",
    "sk": "meta",
    "job_id": "$.JobId",
    "start_timestamp": "$$.Execution.StartTime",
    "archive_id": "$.ArchiveId",
    "vault_name": "$.VaultName",
    "retrieval_type": "$.RetrievalType",
    "archive_size_in_bytes": "$.ArchiveSizeInBytes",
    "description": "$.Description",
    "s3_bucket": "$.S3Bucket",
    "s3_key": "$.S3Key",
    "s3_upload_id": ""$.S3UploadId"",
    "s3_upload_part_size": "$.S3UploadPartSize",
    "s3_upload_part_count": "$.S3UploadPartCount"
}
        initiate_retrieval_dynamo_db_put_task = tasks.DynamoPutItem(
            self,
            "InitiateRetrievalDynamoDBPutTask",
            table=glacier_retrieval_table,
            item={ k: tasks.DynamoAttributeValue.from_string(sfn.JsonPath.string_at(v)) \
                        for k,v in ddb_input_map.items()},
        )         
```

This will prevent a whole lot of code duplication and saves us some line by using python dict comprehension feature.

2023-04-14 13:44 UTC, kamyarz-aws commented
Can you please add integration test here as well

2023-04-14 14:27 UTC, dbb-aws-only commented on source/refreezer/infrastructure/stack.py
>              },
It doesn't seem to like the constant 'meta' - is there a way to fix that?
`E           RuntimeError: Error: JSON path values must be exactly '$', '$$', start with '$.', start with '$$.', start with '$[', or start with an intrinsic function: States.Array, States.ArrayPartition, States.ArrayContains, States.ArrayRange, States.ArrayGetItem, States.ArrayLength, States.ArrayUnique, States.Base64Encode, States.Base64Decode, States.Hash, States.JsonMerge, States.StringToJson, States.JsonToString, States.MathRandom, States.MathAdd, States.StringSplit, States.UUID, or States.Format. Received: meta`

2023-04-14 14:40 UTC, kamyarz-aws commented on source/refreezer/infrastructure/stack.py
>              },
yup 
```
ddb_input_map = {
    "pk": "$.ArchiveId",
    "sk": "meta",
    "job_id": "$.JobId",
    "start_timestamp": "$$.Execution.StartTime",
    "archive_id": "$.ArchiveId",
    "vault_name": "$.VaultName",
    "retrieval_type": "$.RetrievalType",
    "archive_size_in_bytes": "$.ArchiveSizeInBytes",
    "description": "$.Description",
    "s3_bucket": "$.S3Bucket",
    "s3_key": "$.S3Key",
    "s3_upload_id": ""$.S3UploadId"",
    "s3_upload_part_size": "$.S3UploadPartSize",
    "s3_upload_part_count": "$.S3UploadPartCount"
}
initiate_retrieval_dynamo_db_put_task = tasks.DynamoPutItem(
    self,
    "InitiateRetrievalDynamoDBPutTask",
    table=glacier_retrieval_table,
    item={ 
               k: tasks.DynamoAttributeValue.from_string(sfn.JsonPath.string_at(v) if  v!="meta" else v)) \
               for k,v in ddb_input_map.items()
               }
        )         
 ```
 This should do it

2023-04-14 14:47 UTC, dbb-aws-only commented on source/refreezer/infrastructure/stack.py
>              },
Working and Done!

2023-04-18 17:56 UTC, bassemwanis requested changes

2023-04-18 17:56 UTC, bassemwanis commented on source/refreezer/infrastructure/stack.py
> +            "pk": "$.ArchiveId",
We need `workflow_id` to be concatenated to the beginning of pk
https://docs.aws.amazon.com/step-functions/latest/dg/amazon-states-language-intrinsic-functions.html#asl-intrsc-func-string-operation

2023-04-18 17:56 UTC, bassemwanis commented on source/refreezer/infrastructure/stack.py
> +            "archive_id": "$.ArchiveId",
`"archive_id": "$.item.ArchiveId",` since this data will be coming from the `item` of the distributed map

2023-04-18 17:56 UTC, bassemwanis commented on source/refreezer/infrastructure/stack.py
> +            "archive_size_in_bytes": "$.ArchiveSizeInBytes",
`"archive_size_in_bytes": "$.item.Size",`

2023-04-18 17:56 UTC, bassemwanis commented on source/refreezer/infrastructure/stack.py
> +            "description": "$.Description",
`"description": "$.item.ArchiveDescription"`

2023-04-18 17:56 UTC, bassemwanis commented on source/refreezer/infrastructure/stack.py
> +            "s3_upload_id": "$.S3UploadId",
We will not have the s3 `upload_id` at this stage

2023-04-18 17:56 UTC, bassemwanis commented on source/refreezer/infrastructure/stack.py
> +            "s3_upload_part_size": "$.S3UploadPartSize",
same here, we will not have the `S3UploadPartSize` at this stage

2023-04-18 17:56 UTC, bassemwanis commented on source/refreezer/infrastructure/stack.py
> +            "s3_upload_part_count": "$.S3UploadPartCount",
Same

2023-04-18 17:59 UTC, bassemwanis commented on source/tests/integration/infrastructure/test_initiate_retrieval_step_function.py
> +
Please confirm that all parts of this test are reachable and run as expected.

2023-04-21 12:51 UTC, kamyarz-aws commented on source/tests/integration/infrastructure/test_initiate_retrieval_step_function.py
> +def test_state_machine_dynamodb_write_meta(default_input: str) -> None:
I dont think the name is readable. what do you mean by write meta.

2023-04-21 12:53 UTC, dbb-aws-only commented on source/tests/integration/infrastructure/test_initiate_retrieval_step_function.py
> +def test_state_machine_dynamodb_write_meta(default_input: str) -> None:
Good catch!  I'll fix this right now.

2023-04-24 19:02 UTC, closed without merging