Update version to 1.1.3
aws-solutions/amazon-s3-glacier-refreezer pull request #152
Opened 2023-04-19 17:47 UTC by bassemwanis

*Description of changes:*
Updated dependencies:
- Node.js 16
- aws-sdk 2.1357.0

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2023-04-19 18:36 UTC, schana approved these changes

2023-04-19 19:21 UTC, kamyarz-aws approved these changes

2023-04-20 15:35 UTC, simonkrol requested changes

2023-04-20 16:19 UTC, bassemwanis commented on buildspec.yml
> +      nodejs: 16
Good catch, actually I'm currently working on creating a new feature pipeline using v6.3.0 which has Ubuntu standard:6.0 as default

2023-04-20 16:22 UTC, simonkrol commented on buildspec.yml
> +      nodejs: 16
Okay perfect :), as long as the new standard doesn't break anything else, I'm happy

2023-04-24 14:48 UTC, simonkrol approved these changes

2023-04-24 18:28 UTC, bassemwanis commented
Closing this PR, since we end up creating another candidate release branch and created the PR from it to develop.

2023-04-24 18:28 UTC, closed without merging