Implement step function distributed maps using custom states
aws-solutions/amazon-s3-glacier-refreezer pull request #67
Opened 2023-02-03 02:33 UTC by bassemwanis

*Description of changes:*
Utilize custom states to implement the DistributedMap parent class. Additionally, add two pattern classes, one for processing S3 objects and the other for processing CSV files in S3 buckets.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2023-02-03 19:32 UTC, kamyarz-aws commented on source/tests/unit/infrastructure/distributed_map/distributed_map.py
> +        map = sfn.Map(scope, "inline_map_" + self.generate_random_id())
Please use f string for this like following`f"inline_map_{self.generate_random_id()}"`

2023-02-03 19:42 UTC, kamyarz-aws commented on source/tests/unit/infrastructure/distributed_map/distributed_map.py
> +    execution_type: str = "STANDARD"
Is this going to be a constant?

2023-02-03 19:42 UTC, kamyarz-aws commented on source/tests/unit/infrastructure/distributed_map/distributed_map.py
> +    item_reader_resource: str = ""
strings in python are immutable. This way technically two variables are being created. I think you are doing this because you were getting an attribute error. If that is not the case I suggest simply populate the variable in the initializer

2023-02-03 19:42 UTC, kamyarz-aws commented on source/tests/unit/infrastructure/distributed_map/distributed_map.py
> +    item_selector: Dict[str, Any] = {}
generally I dont think there is a need to create this here. Just populate them in your initializer.

2023-02-03 19:42 UTC, kamyarz-aws commented on source/tests/unit/infrastructure/distributed_map/distributed_map.py
> +            "distributed_map_" + self.generate_random_id(),
Please use f string as shown in the other example. (f-string is optimized way of doing this concatenation)

2023-02-03 21:37 UTC, bassemwanis commented on source/tests/unit/infrastructure/distributed_map/distributed_map.py
> +        map = sfn.Map(scope, "inline_map_" + self.generate_random_id())
Done!

2023-02-03 21:43 UTC, bassemwanis commented on source/tests/unit/infrastructure/distributed_map/distributed_map.py
> +    execution_type: str = "STANDARD"
In our case for ReFreezer, we will need to always create Standard workflow due to the limitation of Express workflow (e.g. maximum duration, execution history)
But this can be changed to be a customizable in the future if needed

2023-02-03 21:43 UTC, bassemwanis commented on source/tests/unit/infrastructure/distributed_map/distributed_map.py
> +    item_reader_resource: str = ""
Done!

2023-02-03 21:44 UTC, bassemwanis commented on source/tests/unit/infrastructure/distributed_map/distributed_map.py
> +    item_selector: Dict[str, Any] = {}
Done!

2023-02-03 21:44 UTC, bassemwanis commented on source/tests/unit/infrastructure/distributed_map/distributed_map.py
> +            "distributed_map_" + self.generate_random_id(),
Done!

2023-02-06 15:34 UTC, schana requested changes
Without seeing the larger context, it's hard to see if we're operating at the correct level of abstraction. We should implement the simplest working functionality first (i.e. the CustomState defined manually instead of in a class), and then refactor as the use cases develop. This will give us both the assurance that the functionality still works (through tests) and that we're not overly-engineering the solution.

Regarding this specific approach, the class inheritance structure seems unnecessary for the differences between the children when those attributes could simply be specified by the caller.

2023-02-06 15:34 UTC, schana commented on source/refreezer/infrastructure/distributed_map/distributed_map.py
> +        id: str,
`id` shadows the built-in name and should generally be avoided. As this is implemented, it's probably okay since it's copying the inherited definition, but still worth noting.

2023-02-06 15:34 UTC, schana commented on source/refreezer/infrastructure/distributed_map/distributed_map.py
> +            f"{id}DistributedMap",
What's the purpose of appending to the identifier?

2023-02-06 15:34 UTC, schana commented on source/refreezer/infrastructure/distributed_map/process_file_distributed_map.py
> +from .distributed_map import DistributedMap
We should prefer absolute imports to relative.

2023-02-06 16:31 UTC, bassemwanis commented on source/refreezer/infrastructure/distributed_map/distributed_map.py
> +        id: str,
The main reason here of passing `id` is to provide a mechanism to enable multiple instantiation of `DistributatedMap` within our stack. 
Without it, if we instantiate 2 instances of it for `InitiateRetrieval` and `RetrieveArchive` components, it will fail due to having 2 constructs with same name.

2023-02-06 16:33 UTC, bassemwanis commented
>

2023-02-06 16:53 UTC, bassemwanis commented on source/refreezer/infrastructure/distributed_map/process_file_distributed_map.py
> +from .distributed_map import DistributedMap
I will fix it!

2023-02-06 17:30 UTC, schana commented on source/refreezer/infrastructure/distributed_map/distributed_map.py
> +        id: str,
This comment refers to the naming choice of `id`, not the reasons for why it exists. Your editor should show this as a warning.

2023-02-06 17:31 UTC, schana commented on source/refreezer/infrastructure/distributed_map/distributed_map.py
> +            f"{id}DistributedMap",
Right, but why does the outer map need it appended? Could this just be the `id`, with the inner one being something like `f"{id}Inner"`?

2023-02-06 17:35 UTC, bassemwanis commented on source/refreezer/infrastructure/distributed_map/distributed_map.py
> +        id: str,
Ah, I though you are talking about the concept itself of passing the `id` :)

2023-02-06 17:37 UTC, bassemwanis commented on source/refreezer/infrastructure/distributed_map/distributed_map.py
> +            f"{id}DistributedMap",
Sure, I agree that way it would be simpler.

2023-02-06 22:21 UTC, bassemwanis commented
This revision include the following changes:

- Add Inventory Bucket + Access log bucket
- Add `NestedDistributedMap` construct
- Add unit tests to cover all changes
- Remove DistributedMap parent class and its 2 children classes

2023-02-07 16:29 UTC, bassemwanis commented
I added another commit with the basic Integration tests

2023-02-09 19:15 UTC, kamyarz-aws commented on source/refreezer/infrastructure/nested_distributed_map.py
> +                        + "/*"
Please use f-string for this.

2023-02-09 19:17 UTC, kamyarz-aws commented on source/refreezer/infrastructure/nested_distributed_map.py
> +                        + "/*"
https://stackoverflow.com/questions/45965007/multiline-f-string-in-python

you can multiline it following this, and using \ at the end of the line

2023-02-09 19:19 UTC, kamyarz-aws commented on source/refreezer/infrastructure/nested_distributed_map.py
> +        csv_result_path = "$.map_result"
if this is a constant and reusable in other places, please define it as GLOBAL variable with variable name that is all capital letters. https://realpython.com/python-constants/ . If local and still constant, just follow the naming mechanism please.

2023-02-09 19:21 UTC, kamyarz-aws commented on source/refreezer/infrastructure/nested_distributed_map.py
> +        s3_item_reader_resource = "arn:aws:states:::s3:listObjectsV2"
same comment on this

2023-02-09 19:45 UTC, kamyarz-aws approved these changes

2023-04-24 18:29 UTC, closed without merging