Draft: feature/kamyarz
aws-solutions/amazon-s3-glacier-refreezer pull request #68
Opened 2023-02-08 03:27 UTC by kamyarz-aws

*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2023-02-08 16:07 UTC, schana commented
Closing and re-opening to run the status checks with the correct target branch.

2023-03-01 16:30 UTC, schana submitted a review, later dismissed

2023-03-01 16:30 UTC, schana commented on source/refreezer/aws_lambda/facilitator_lambda/lambda_function.py
> +            raise Exception("FAILED:: The job has failed")
Is there not an explicit failed state for the job? This would be great to pull out so the logic and possible states are all contained together.

2023-03-01 16:30 UTC, schana commented on source/refreezer/aws_lambda/facilitator_lambda/lambda_function.py
> +            sfn_client.send_task_failure(taskToken=task_token, error="", cause="")
This seems a bit presumptuous to send a failure for any exception. Can we be more granular?

2023-03-01 16:30 UTC, schana commented on source/refreezer/aws_lambda/facilitator_lambda/lambda_function.py
> +        sfn_client.send_task_failure(taskToken=task_token, error="", cause="")
Does this follow the designed logic tree?

2023-03-01 16:30 UTC, schana commented on source/refreezer/aws_lambda/facilitator_lambda/lambda_function.py
> +        # Hardcoded region for now
Why do we need to specify the region here? I thought `boto` should be able to pick it up from the lambda environment?

2023-03-02 14:57 UTC, kamyarz-aws commented on .viperlightignore
> +.tox
I ran the viperlight on prehook commit and it threw errors for enviromental folders. If we dont need it, I will remove the hook locally and delete the files. However. I am pretty sure we will need to add it later for release pipeline to pass. We can do it in separate PR but it better be done.

2023-03-02 14:58 UTC, kamyarz-aws commented on .viperlightrc
> +{"failOn":"low","all":true}
Will be removed

2023-03-02 15:07 UTC, kamyarz-aws commented on source/refreezer/aws_lambda/facilitator_lambda/lambda_function.py
> +    QueryOutputTableTypeDef = object
Only DynamoDBClient wasnt matching. I address that. `We should probably add a test to ensure this behavior (it's for pylint compatibility)` As for the coded part I am not following, can you please elaborate.

2023-03-02 15:07 UTC, kamyarz-aws commented on source/tests/unit/conftest.py
> +def assert_resource_name_has_correct_type_and_props(
I agree we could do that. But even doing this was outside the scope of this task. Is it okay if we do it in another PR?

2023-03-02 15:11 UTC, kamyarz-aws commented on source/refreezer/aws_lambda/facilitator_lambda/lambda_function.py
> +        raise ValueError(err_msg)
It is my habit of writing lambdas honestly. But at the same time, I dont see any problem with a little safety check at first. If you want me to do delete it, I would

2023-03-02 15:13 UTC, kamyarz-aws commented on source/refreezer/aws_lambda/facilitator_lambda/lambda_function.py
> +REGION = "REGION"
which part defining the constants? or defining REGION itself?

2023-03-02 18:45 UTC, kamyarz-aws commented on source/refreezer/aws_lambda/facilitator_lambda/lambda_function.py
> +"""
Done

2023-03-02 18:48 UTC, kamyarz-aws commented on source/refreezer/aws_lambda/facilitator_lambda/lambda_function.py
> +            raise Exception("FAILED:: The job has failed")
I am not sure if I am following but what I do here is to raise the exception and then in the exception I will send_task_failure.

2023-03-02 18:49 UTC, kamyarz-aws commented on source/refreezer/aws_lambda/facilitator_lambda/lambda_function.py
> +            sfn_client.send_task_failure(taskToken=task_token, error="", cause="")
Without sending it, stepfunctions will stuck on certain errors. I thought it would be better to send task failure for most errors cause I dont think letting step function to hang would be a good idea.

2023-03-02 22:21 UTC, kamyarz-aws commented on source/refreezer/aws_lambda/facilitator_lambda/lambda_function.py
> +    QueryOutputTableTypeDef = object
I will create asana ticket for it and post it here later.

2023-03-02 22:23 UTC, kamyarz-aws commented on source/tests/unit/conftest.py
> +def assert_resource_name_has_correct_type_and_props(
I will put back the non fixtures back to stack.py and we later discussed if we need to do anything further.

2023-03-02 22:27 UTC, kamyarz-aws commented on source/refreezer/aws_lambda/facilitator_lambda/lambda_function.py
> +DDB_TABLE_NAME = "DDB_TABLE_NAME"
Match it with self.outputs database table

2023-03-02 22:29 UTC, kamyarz-aws commented on source/refreezer/aws_lambda/facilitator_lambda/lambda_function.py
> +) -> None:
Data Access Layer

2023-03-02 22:32 UTC, kamyarz-aws commented on source/refreezer/aws_lambda/facilitator_lambda/lambda_function.py
> +            raise Exception("FAILED:: The job has failed")
adrress more status codes and try to modularize it maybe in another function.

2023-03-03 02:12 UTC, kamyarz-aws commented on source/refreezer/aws_lambda/facilitator_lambda/lambda_function.py
> +    QueryOutputTableTypeDef = object
https://app.asana.com/0/1202938635037719/1204103127973286/f

2023-03-03 02:15 UTC, kamyarz-aws commented on tox.ini
> +    pip install ".[dev]"
Done

2023-03-03 02:15 UTC, kamyarz-aws commented on source/refreezer/aws_lambda/facilitator_lambda/lambda_function.py
> +        raise ValueError(err_msg)
Done

2023-03-07 20:44 UTC, kamyarz-aws commented on source/refreezer/aws_lambda/facilitator_lambda/lambda_function.py
> +        # Hardcoded region for now
https://amzn-aws.slack.com/archives/C04LA6XK4LA/p1678215948513909

Addressed as part of Simon Tasks.

2023-03-09 17:38 UTC, simonkrol commented on tox.ini
> +extras =
What is this for?

2023-03-09 17:50 UTC, simonkrol commented on source/refreezer/application/facilitator/processor.py
> +def _populating_async_facilitator_table(glacier_item: GlacierJobItem) -> None:
Consider populate rather than populating

2023-03-15 21:35 UTC, bassemwanis requested changes

2023-03-15 21:35 UTC, bassemwanis commented on source/refreezer/application/facilitator/processor.py
> +    facilitator_model.finish_timestamp = record["Sns"]["Timestamp"]
Can we set `facilitator_model.finish_timestamp` to `job_result["CompletionDate"]` to get the actual time when Glacier job is completed.
Also will need to move it after the check `check_if_job_finished `

2023-03-15 21:35 UTC, bassemwanis commented on source/refreezer/application/facilitator/processor.py
> +                "status": job_result,
can we change the key to `job_result` as well?

2023-03-15 21:35 UTC, bassemwanis commented on source/refreezer/application/facilitator/processor.py
> +                    "status": "Success",
Can you return the `job_result` here as well?

2023-03-15 21:35 UTC, bassemwanis commented on source/refreezer/application/facilitator/processor.py
> +    if not facilitator_model.check_if_job_finished():
I suggest renaming `check_if_job_finished` method to `check_still_in_progress` to provide better clarity!
```
if facilitator_model.check_still_in_progress():
    return
```

2023-03-15 21:35 UTC, bassemwanis commented on source/refreezer/application/facilitator/processor.py
> +            taskToken=facilitator_model.task_token, error="", cause=""
Can we set the `error` to `job_result["StatusMessage"]`?

2023-03-15 21:35 UTC, bassemwanis commented on source/refreezer/application/facilitator/processor.py
> +    sfn_client.send_task_failure(taskToken=task_token, error="", cause="")
Should we move the failure block to be inside an `elif`?

2023-03-16 01:19 UTC, kamyarz-aws commented on source/refreezer/application/facilitator/processor.py
> +    if not facilitator_model.check_if_job_finished():
Can I create a ticket and do this as part of that? If I want to address this, I should fix it in data model too hence more files would show in the PR

2023-03-16 01:22 UTC, kamyarz-aws commented on source/refreezer/application/facilitator/processor.py
> +    sfn_client.send_task_failure(taskToken=task_token, error="", cause="")
I thought send_task_success works as a return. for safety I put them in an else.

2023-03-16 13:48 UTC, dbb-aws-only commented on source/refreezer/application/facilitator/processor.py
> +    if not facilitator_model.check_if_job_finished():
Creating an Asana task for this sounds fine.

2023-03-16 13:50 UTC, dbb-aws-only commented on source/tests/unit/application/facilitator/test_processor.py
> +            "Timestamp": "12:12:12",
What does 12:12:12 represent?

2023-03-16 13:52 UTC, dbb-aws-only commented on source/tests/unit/application/facilitator/test_processor.py
> +
Can we use better test data?  "S", "M" and "N" are not very descriptive...  Can we use actual timestamps?

2023-03-16 13:55 UTC, dbb-aws-only approved these changes
There's a lot of code changes in this one - hopefully we can create smaller PRs in the future...

2023-03-16 14:53 UTC, bassemwanis commented on source/tests/unit/application/facilitator/test_processor.py
> +
[Suggestion] Can we move the duplicated code within the 3 sns record fixtures to a helper function and call it instead?
something like that:
```
def sns_record(glacier_job_result: Dict[str, Any], status_code: Optional[str] = None) -> Dict[str, Any]:
    if status_code:
        glacier_job_result["StatusCode"] = status_code
    return {
        "EventSource": "aws:sns",
        "Sns": {
            "Message": json.dumps(glacier_job_result),
            "Timestamp": "12:12:12",
        },
    }

@pytest.fixture
def sns_default_record(glacier_job_result: Dict[str, Any]) -> Dict[str, Any]:
    return sns_record(glacier_job_result)

@pytest.fixture
def sns_failed_record(glacier_job_result: Dict[str, Any]) -> Dict[str, Any]:
    return sns_record(glacier_job_result, "Failed")

@pytest.fixture
def sns_in_progress_record(glacier_job_result: Dict[str, Any]) -> Dict[str, Any]:
    return sns_record(glacier_job_result, "InProgress")
```

2023-03-16 14:53 UTC, bassemwanis commented on source/tests/unit/infrastructure/test_stack.py
> -    return stack
What is the reason behind removing `stack` fixture?

2023-03-16 14:53 UTC, bassemwanis commented on source/tests/unit/infrastructure/test_stack.py
> -    return assertions.Template.from_stack(stack)
Same here, what is the reason behind removing `template` fixture?

2023-03-16 14:53 UTC, bassemwanis commented on tox.ini
> +    dev
I think you don't need this any more since we added `cdk-nag` to the main `dependencies`

2023-03-16 14:53 UTC, bassemwanis commented on source/refreezer/application/facilitator/processor.py
> +        logger.info("Cannot find the job task token")
[Suggestion] Can we change this message to `Cannot find the task token for job: {job_result['JobId']}` to provide more detailed information when handling hundreds of parallel async calls.

2023-03-16 14:53 UTC, bassemwanis commented on source/refreezer/application/facilitator/processor.py
> +def _populate_async_facilitator_table(facilitator_model: FacilitatorModel) -> None:
[Suggestion] Consider changing the name of `_populate_async_facilitator_table` function to something like `_update_db_entry` for better clarity.

2023-03-16 14:53 UTC, bassemwanis commented on source/refreezer/application/facilitator/processor.py
> +    facilitator_model = FacilitatorModel(job_id=job_result["JobId"])
[Suggestion] Consider changing the name of `facilitator_model` variable to something like `tracking_model` for better clarity.

2023-03-16 15:19 UTC, simonkrol commented on source/refreezer/application/facilitator/processor.py
> +    if not (
Would it be more readable to say: `if ("NewImage" not in record["dynamodb"] or "finish_timestamp" not in record["dynamodb"]["NewImage"])`

You could also replace this entirely with:
```
if new_image := record.get("dynamodb", {}).get("NewImage") is None:
    logger.info("The job is still in progress")
    return
```
Which would let you use the new_image down the line everywhere else you have `record["dynamodb"]["NewImage"]`

2023-03-16 15:19 UTC, simonkrol commented on source/refreezer/application/handlers.py
> +    DynamoDBServiceResource = object
What is this for?

2023-03-16 15:19 UTC, simonkrol commented on source/tests/unit/application/facilitator/test_processor.py
> +    from mypy_boto3_dynamodb import DynamoDBServiceResource
This doesn't look like it's being used in this file

2023-03-16 15:19 UTC, simonkrol commented on source/tests/unit/conftest.py
> +def glacier_job_result() -> typing.Dict[str, typing.Any]:
Is this fixture something we anticipate being reused?

2023-03-16 16:09 UTC, kamyarz-aws commented on source/tests/unit/infrastructure/test_stack.py
> -    return assertions.Template.from_stack(stack)
I actually talked about it with Nathaniel as well. For instance when we have new construct. We will have to write tests for those constructs and stack and template fixture can be reused for those construct and not necessarily needed to be bounded only by test_stack.py

2023-03-16 16:09 UTC, kamyarz-aws commented on source/tests/unit/infrastructure/test_stack.py
> -    return stack
I actually talked about it with Nathaniel as well. For instance when we have new construct. We will have to write tests for those constructs and stack and template fixture can be reused for those construct and not necessarily needed to be bounded only by test_stack.py

2023-03-16 16:17 UTC, bassemwanis commented on source/tests/unit/infrastructure/test_stack.py
> -    return stack
But do you need to add them to `conftest.py` or something?

2023-03-16 17:37 UTC, kamyarz-aws commented on source/refreezer/application/facilitator/processor.py
> +    if not facilitator_model.check_if_job_finished():
https://app.asana.com/0/1202938635037719/1204197294327693/f

2023-03-16 17:47 UTC, kamyarz-aws commented on source/refreezer/application/facilitator/processor.py
> +    facilitator_model = FacilitatorModel(job_id=job_result["JobId"])
why tracking_model is a better name?

2023-03-16 18:20 UTC, bassemwanis commented on source/refreezer/application/facilitator/processor.py
> +    facilitator_model = FacilitatorModel(job_id=job_result["JobId"])
Since the primary intent of this table is to store job-to-task **_tracking_** information. according to this https://app.asana.com/0/1202938635037719/1203689150582174/f

But again this was a suggestion, you can ignore it if you don't like it :)

2023-03-16 18:59 UTC, kamyarz-aws commented on source/tests/unit/application/facilitator/test_processor.py
> +
Those are dynamoDB input json Style Cannot be modified.

2023-03-16 19:01 UTC, kamyarz-aws commented on source/tests/unit/conftest.py
> +def glacier_job_result() -> typing.Dict[str, typing.Any]:
Yes I actually have to use this for test_faciliator_model as well. The reason that I havent adjusted it here, is that it creates a new file and make this PR bigger. I create a task for it to go back and adjust it later https://app.asana.com/0/1202938635037719/1204197294327693/f

2023-03-16 19:21 UTC, simonkrol approved these changes

2023-03-16 19:21 UTC, bassemwanis approved these changes

2023-03-16 19:46 UTC, merged