Implement inventory retrieval chunk determination lambda
aws-solutions/amazon-s3-glacier-refreezer pull request #71
Opened 2023-02-14 02:23 UTC by bassemwanis

*Description of changes:*
- Implement inventory retrieval chunk determination lambda
- Add Unit tests and integration tests

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2023-02-14 14:27 UTC, simonkrol commented on source/refreezer/infrastructure/stack.py
> +        inventory_chunk_determination_lambda = _lambda.Function(
Should we be looking at enabling Xray tracing for this lambda?

2023-02-14 14:59 UTC, kamyarz-aws approved these changes

2023-02-14 16:37 UTC, bassemwanis commented on source/refreezer/infrastructure/stack.py
> +        inventory_chunk_determination_lambda = _lambda.Function(
There is a separate task to add metrics collection and other solutions requirements: https://app.asana.com/0/1202938635037719/1203922469484738/f

2023-02-14 16:37 UTC, bassemwanis commented on source/refreezer/aws_lambda/inventory_chunk_determination/lambda_function.py
> +    try:
Will do!

2023-02-14 16:52 UTC, schana requested changes

2023-02-14 16:52 UTC, schana commented on source/refreezer/infrastructure/stack.py
> +from aws_cdk import aws_lambda as _lambda
This should be `lambda_`. Prepending it has a conventional meaning of being private.

2023-02-14 16:52 UTC, schana commented on source/refreezer/aws_lambda/inventory_chunk_determination/lambda_function.py
> +"""
The handler and logic should be broken into separate functions. The logic should live in some place like `source/refreezer/application/chunking/inventory.py`, and the handlers could be put together in a place like `source/refreezer/application/handlers.py`. If the `handlers.py` gets too complex, we can put it in a `handler` package with individual modules.

2023-02-14 16:52 UTC, schana commented on source/refreezer/aws_lambda/inventory_chunk_determination/lambda_function.py
> +            400,
Would this be a 400?

2023-02-14 16:52 UTC, schana commented on source/refreezer/aws_lambda/inventory_chunk_determination/lambda_function.py
> +    return {"statusCode": status_code, "body": response_data}
What's the purpose behind explicitly defining the status codes here? Can we not just return the json or throw an exception and let the lambda runtime figure it out? This would simplify the handler considerably, making it responsible only for parsing the parameters and returning the response from the logic module.

2023-02-14 16:52 UTC, schana commented on source/refreezer/infrastructure/stack.py
> +            ),
We'll likely want a way to include the entire package in our lambda instead of singular files - does this do that, or will we need to build a layer?

2023-02-14 16:52 UTC, schana commented on source/refreezer/infrastructure/stack.py
> +            inventory_chunk_determination_lambda.role.node.find_child(  # type: ignore
We should explicitly define the type here instead of ignoring the check.

2023-02-14 16:52 UTC, schana commented on source/refreezer/infrastructure/stack.py
> +                    "reason": "Default Lambda AWS managed policies are required for AWSLambdaBasicExecutionRole.",
Why are they required?

2023-02-14 16:52 UTC, schana commented on source/tests/integration/infrastructure/test_inventory_chunk_determination_lambda.py
> +    chunk_size = 10485760  # 10 MB
The fine-grained unit testing should be split out and handled. This should just test the lambda invocation (based on the test name). Further, you could write the numbers without the need for comments, like `2 ** 30 * 10`.

2023-02-14 19:53 UTC, bassemwanis commented on source/refreezer/infrastructure/stack.py
> +from aws_cdk import aws_lambda as _lambda
Will fix!

2023-02-14 19:55 UTC, bassemwanis commented on source/refreezer/infrastructure/stack.py
> +                    "reason": "Default Lambda AWS managed policies are required for AWSLambdaBasicExecutionRole.",
CDK grants an AWS managed policy for AWSLambdaBasicExecutionRole. Do you want me to modify the reason message to make it more clear?

2023-02-14 19:55 UTC, bassemwanis commented on source/tests/integration/infrastructure/test_inventory_chunk_determination_lambda.py
> +    chunk_size = 10485760  # 10 MB
Will fix!

2023-02-14 19:58 UTC, bassemwanis commented on source/refreezer/infrastructure/stack.py
> +            inventory_chunk_determination_lambda.role.node.find_child(  # type: ignore
I was getting the following error `Item "None" of "Optional[IRole]" has no attribute "node"`
I will do more research on how to fix it.

2023-02-15 00:39 UTC, bassemwanis commented on source/refreezer/aws_lambda/inventory_chunk_determination/lambda_function.py
> +"""
Will Fix!

2023-02-15 00:40 UTC, bassemwanis commented on source/refreezer/aws_lambda/inventory_chunk_determination/lambda_function.py
> +            400,
Will remove explicitly defining the status codes.

2023-02-15 01:33 UTC, bassemwanis commented on source/refreezer/infrastructure/stack.py
> +            inventory_chunk_determination_lambda.role.node.find_child(  # type: ignore
When I use `assert isinstance(inventory_chunk_determination_lambda.role, iam.IRole)` I get this error `Instance and class checks can only be used with @runtime_checkable protocols`

However, `assert inventory_chunk_determination_lambda.role is not None` worked

2023-02-15 01:52 UTC, bassemwanis commented on source/refreezer/aws_lambda/inventory_chunk_determination/lambda_function.py
> +    try:
Done!

2023-02-15 01:52 UTC, bassemwanis commented on pyproject.toml
> +    "boto3-stubs[lambda]",
Done!

2023-02-15 01:52 UTC, bassemwanis commented on source/refreezer/infrastructure/stack.py
> +from aws_cdk import aws_lambda as _lambda
Done!

2023-02-15 01:52 UTC, bassemwanis commented on source/refreezer/aws_lambda/inventory_chunk_determination/lambda_function.py
> +"""
Done!

2023-02-15 01:52 UTC, bassemwanis commented on source/refreezer/aws_lambda/inventory_chunk_determination/lambda_function.py
> +            400,
Done!

2023-02-15 01:53 UTC, bassemwanis commented on source/refreezer/aws_lambda/inventory_chunk_determination/lambda_function.py
> +    return {"statusCode": status_code, "body": response_data}
Done! let Lambda runtime handles status codes

2023-02-15 01:54 UTC, bassemwanis commented on source/refreezer/infrastructure/stack.py
> +            ),
Changed it to include all source folder `code=lambda_.Code.from_asset("source"),`

2023-02-15 01:54 UTC, bassemwanis commented on source/tests/integration/infrastructure/test_inventory_chunk_determination_lambda.py
> +    chunk_size = 10485760  # 10 MB
Done!

2023-02-15 18:41 UTC, simonkrol approved these changes

2023-02-15 18:41 UTC, simonkrol commented on source/refreezer/infrastructure/stack.py
> +    INVENTORY_CHUNCK_DETERMINATION_LAMBDA_ARN = "InventoryChunkDeterminationLambdaArn"
Typo on chunck

2023-02-15 18:41 UTC, simonkrol commented on source/tests/unit/application/test_inventory_generate_chunk_array.py
> +    last_chunck_entry = 1 if last_chunk_size - maximum_inventory_record_size > 0 else 0
Typo on chunck

2023-02-15 20:00 UTC, bassemwanis commented on source/refreezer/infrastructure/stack.py
> +    INVENTORY_CHUNCK_DETERMINATION_LAMBDA_ARN = "InventoryChunkDeterminationLambdaArn"
Fixed!

2023-02-24 17:37 UTC, simonkrol submitted a review, later dismissed

2023-03-06 14:52 UTC, schana submitted a review, later dismissed

2023-03-06 22:11 UTC, bassemwanis commented
Just pushed a new revision after fixing merge conflicts.

2023-03-07 17:44 UTC, schana approved these changes

2023-03-07 17:44 UTC, simonkrol approved these changes

2023-03-07 19:29 UTC, bassemwanis commented
Removed the merge commit and replaced it with rebase

2023-03-07 20:12 UTC, simonkrol approved these changes

2023-03-07 21:06 UTC, schana approved these changes

2023-03-07 21:11 UTC, merged