Adding a bootstrap stack for the base pipeline
aws-solutions/amazon-s3-glacier-refreezer pull request #72
Opened 2023-02-14 19:21 UTC by evanwieren

Added a stack so the SSM parameters would not have to be created manually. The docs will need to be updated to recommend the build process is to deploy bootstrap and then pipeline.

Also added name of the app to bootstrap to prevent name collisions

*Issue #, if available:* N/A

*Description of changes:*

Added a new stack that creates the SSM params needed by the pipeline stack. Included tests and formatting. 

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2023-02-14 20:43 UTC, schana requested changes
This PR should also include the updates to the documentation.

2023-02-14 20:43 UTC, schana commented on source/tests/unit/bootstrap/test_stack.py
> +    assert 4 == len(resources)
Is this testing the same thing twice? What does this do differently than the `template.resource_count_is()` call?

2023-02-14 20:43 UTC, schana commented on source/tests/unit/bootstrap/test_stack.py
> +    template = assertions.Template.from_stack(stack)
This should use the fixture.

2023-02-14 20:43 UTC, schana commented on source/tests/unit/bootstrap/test_stack.py
> +def base_template() -> assertions.Template:
We could probably just name this, `template`.

2023-02-14 21:21 UTC, schana approved these changes

2023-02-14 21:21 UTC, evanwieren commented on source/tests/unit/bootstrap/test_stack.py
> +    assert 4 == len(resources)
Removed, I was playing with tests.

2023-02-14 21:21 UTC, evanwieren commented on source/tests/unit/bootstrap/test_stack.py
> +    template = assertions.Template.from_stack(stack)
Done

2023-02-14 21:21 UTC, evanwieren commented on source/tests/unit/bootstrap/test_stack.py
> +def base_template() -> assertions.Template:
Done.

2023-02-15 18:04 UTC, G-Lenz commented on source/refreezer/app.py
> +    BootstrapStack(app, "refreezer-bootstrap")
Should this be a stack or a construct? It does not seem to be independently functioning resources but rather a necessary piece of part of another stack

2023-02-15 18:05 UTC, G-Lenz approved these changes

2023-02-15 18:06 UTC, merged