Build a Mocking Glacier Stack with an empty Lambda function
aws-solutions/amazon-s3-glacier-refreezer pull request #77
Opened 2023-02-28 20:21 UTC by bassemwanis

*Description of changes:*
Build a Mocking Glacier Stack with an empty Lambda function
Build LambdaInvoke task in Mocking Stack

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2023-03-01 16:41 UTC, schana requested changes

2023-03-01 16:41 UTC, schana commented on source/refreezer/infrastructure/mock_glacier_stack.py
> +"""
Likewise, this should probably be in its own package, similar to how the pipeline is in its own.

2023-03-01 16:41 UTC, schana commented on source/refreezer/infrastructure/mock_glacier_stack.py
> +            "MockGalcierService",
Spelling

2023-03-01 16:41 UTC, schana commented on source/refreezer/infrastructure/mock_glacier_stack.py
> +        }
What's the reason for having a dictionary instead of just having the parameters be named explicitly?

2023-03-01 19:19 UTC, bassemwanis commented on source/refreezer/infrastructure/mock_glacier_stack.py
> +        }
I decided to combine them in a `params` dictionary to keep the `reFreezer` stack constructor simple and clean, especially if we need to pass more info from the mock stack to the main stack

2023-03-03 19:18 UTC, bassemwanis commented on source/refreezer/infrastructure/mock_glacier_stack.py
> +        }
Replaced the dictionary with a class to ensure type checking.

2023-03-06 14:56 UTC, schana approved these changes

2023-03-07 14:53 UTC, kamyarz-aws commented on source/refreezer/application/mocking/handlers.py
> +    vault_name = event.get("VaultName", "testing_vault_name")
I know creating variables will give more visibility, but I suggest that you just do something like to avoid object creation
 `return generate_inventory_retrieval_response(event.get("AccountId", "testing_account_id"), event.get("VaultName", "testing_vault_name"))`

2023-03-07 14:55 UTC, kamyarz-aws approved these changes

2023-03-07 15:12 UTC, bassemwanis commented on source/refreezer/application/mocking/handlers.py
> +    vault_name = event.get("VaultName", "testing_vault_name")
Thanks for bringing that up, I'll keep it in mind moving forward.

2023-03-07 15:13 UTC, merged