Add Inventory Chunk Download Lambda Skeleton plus unit tests
aws-solutions/amazon-s3-glacier-refreezer pull request #83
Opened 2023-03-08 20:50 UTC by dbb-aws-only

Add the skeleton for Inventory Chunk Download Lambda and add unit test cases.

2023-03-08 21:26 UTC, bassemwanis requested changes
Can you squash your commits into 1 commit?

2023-03-08 21:26 UTC, bassemwanis commented on source/refreezer/infrastructure/stack.py
> +                    "reason": "CDK grants AWS managed policy for Lambda basic execution by default. Replacing it with a customer managed policy will be addressed later.",
The reason needs to address AwsSolutions-IAM5, explaining why the IAM entity contains wildcard permissions.

2023-03-08 21:26 UTC, bassemwanis commented on source/refreezer/infrastructure/stack.py
> -            parameters={"InventoryRetrieved": "TRUE"},
Did removing this line break the pipeline integration test?

2023-03-08 21:26 UTC, bassemwanis commented on source/refreezer/infrastructure/stack.py
> +        # create an empty lambda function to pass into the invoke
No need to have this comment

2023-03-08 21:26 UTC, bassemwanis commented on source/refreezer/infrastructure/stack.py
> +            ),  #  .role.node.find_child("Resource"),
No need to have this comment

2023-03-09 20:55 UTC, bassemwanis commented on source/refreezer/infrastructure/stack.py
> +        # result_selector={"InventoryRetrieved": "TRUE"},
Please remove this comment.

2023-03-09 22:21 UTC, bassemwanis requested changes

2023-03-09 22:21 UTC, bassemwanis commented on source/tests/unit/infrastructure/test_stack.py
> +                                    r'"Parameters":{"FunctionName"'
There is a missing `:"` at the end of this line
`r'"Parameters":{"FunctionName":"'`

2023-03-09 22:21 UTC, bassemwanis commented on source/tests/unit/infrastructure/test_stack.py
> +                                    r'"Payload.\$":"\$"}}}},'
There is a missing `",` at this line
`r'","Payload.\$":"\$"}},'`

2023-03-09 22:21 UTC, bassemwanis commented on source/tests/unit/infrastructure/test_stack.py
> +                                    r'"IntervalSeconds":\d,"MaxAttempts":\d,"BackoffRate":\d}\],"Type":"Task",'
There is a missing `"Resource":"arn:` at the end of this line
`r'"IntervalSeconds":\d,"MaxAttempts":\d,"BackoffRate":\d}\],"Type":"Task","Resource":"arn:'`

2023-03-10 20:52 UTC, dbb-aws-only commented on source/refreezer/infrastructure/stack.py
> +        assert inventory_chunk_download_lambda_function.role is not None
The assert is only there for tox -e type

2023-03-10 20:53 UTC, dbb-aws-only commented on source/refreezer/infrastructure/stack.py
> -            parameters={"InventoryRetrieved": "TRUE"},
It did - as you suggested, I added the return value to the lambda handler.

2023-03-10 22:40 UTC, dbb-aws-only commented on source/refreezer/infrastructure/stack.py
> +        # create an empty lambda function to pass into the invoke
Done.

2023-03-10 22:40 UTC, dbb-aws-only commented on source/refreezer/infrastructure/stack.py
> +                    "reason": "CDK grants AWS managed policy for Lambda basic execution by default. Replacing it with a customer managed policy will be addressed later.",
Done.

2023-03-13 14:31 UTC, kamyarz-aws commented on source/refreezer/infrastructure/stack.py
> +                        + ".Arn>:*"
use f-string instead of + for string concatenation.

2023-03-13 14:31 UTC, kamyarz-aws commented on source/refreezer/infrastructure/stack.py
> +                        + ".Arn>:*"
![image](https://user-images.githubusercontent.com/120507168/224732307-1351e30d-8ba5-40f1-906f-475eb69eabad.png)

2023-03-13 14:33 UTC, bassemwanis approved these changes

2023-03-13 16:31 UTC, kamyarz-aws approved these changes

2023-03-13 18:38 UTC, kamyarz-aws commented on source/refreezer/infrastructure/stack.py
> +                        + ".Arn>:*"
This comment is not addressed?

2023-03-13 18:43 UTC, bassemwanis requested changes

2023-03-13 18:43 UTC, bassemwanis commented on source/refreezer/infrastructure/stack.py
Please remove these 2 lines

2023-03-13 18:43 UTC, bassemwanis commented on source/tests/unit/infrastructure/test_stack.py
> +    #             ),
Please remove this commented block.

2023-03-13 19:25 UTC, dbb-aws-only commented on source/refreezer/infrastructure/stack.py
> +                        + ".Arn>:*"
I did change the source code and it's in this PR - this is the new line of code: 
{"Fn::GetAtt": [inventory_lambda_logical_id, "Arn"]},

2023-03-13 20:01 UTC, dbb-aws-only commented on source/refreezer/infrastructure/stack.py
Done.  Oops.

2023-03-13 21:32 UTC, bassemwanis approved these changes

2023-03-13 21:32 UTC, bassemwanis commented on source/refreezer/infrastructure/stack.py
> +                        + ".Arn>:*"
It should be something like that: `f"Resource::<{inventory_chunk_download_lambda_function_logical_id}.Arn>:*"`

2023-03-14 14:59 UTC, bassemwanis approved these changes

2023-03-14 16:31 UTC, merged