Inventory Chunk Determination Lambda Task
aws-solutions/amazon-s3-glacier-refreezer pull request #90
Opened 2023-03-15 18:54 UTC by dbb-aws-only

Create the chunk determination lambda task. This will take the size of the inventory and the chunk size and calculate the chunk ranges that can be downloaded.  This is an input into the MAP to actually download the inventory.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2023-03-15 20:18 UTC, bassemwanis requested changes

2023-03-16 15:32 UTC, dbb-aws-only commented on source/refreezer/application/handlers.py
> +def inventory_chunk_download_lambda_handler(
Removed.

2023-03-16 17:27 UTC, bassemwanis commented on source/tests/unit/infrastructure/test_stack.py
>                                  r'"DistributedMap":{"Type":"Map","Next":"GlueOrderArchives","Iterator":{"StartAt":"InventoryChunkDownloadLambda",'
Do we need to add something like `",` to the beginning of this line?

2023-03-16 17:27 UTC, bassemwanis commented on source/tests/unit/infrastructure/test_stack.py
>                                  r'"IntervalSeconds":\d+,"MaxAttempts":\d+,"BackoffRate":\d+}],"Type":"Task","Resource":'
Do we need to add `"` to the end of this line?

2023-03-16 17:27 UTC, bassemwanis commented on source/tests/unit/infrastructure/test_stack.py
> +                                r'"ItemsPath":"\$.body"},'
Do we need to add `"}}},` to the beginning of this line?

2023-03-16 18:24 UTC, dbb-aws-only commented on source/tests/integration/infrastructure/test_inventory_retrieval_step_function.py
> +    sf_output = "TIMEOUT EXCEEDED"
If the timeout was exceeded before, the sf_output was never initialized and the function failed instead of reporting a timeout.  This fixes that.

2023-03-16 18:25 UTC, dbb-aws-only commented on source/tests/integration/infrastructure/test_inventory_retrieval_step_function.py
> +    sf_output = get_state_machine_output(response["executionArn"], timeout=20)
As the step function becomes more complex, we'll need to increase this number carefully.

2023-03-16 19:26 UTC, bassemwanis approved these changes

2023-03-17 12:45 UTC, dbb-aws-only commented on source/refreezer/application/handlers.py
> +    # maximum_inventory_record_size = event["MaximumInventoryRecordSize"]
Done

2023-03-17 12:46 UTC, dbb-aws-only commented on source/refreezer/application/handlers.py
> +    return {"body": ""}
Yup - I had Git issues, I've fixed this

2023-03-17 16:06 UTC, simonkrol approved these changes

2023-03-17 16:22 UTC, merged