Add inventory chunks trimming logic based on newline delimiters
aws-solutions/amazon-s3-glacier-refreezer pull request #98
Opened 2023-03-21 19:01 UTC by bassemwanis

*Description of changes:*
Add inventory chunks trimming logic based on newline delimiters

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2023-03-22 14:29 UTC, dbb-aws-only commented on source/refreezer/application/chunking/trim.py
> +        chunk = chunk[chunk.rindex(b"\n", 0, max_record_size) + 1 :]
Is it possible there will be no \n in a chunk?  The rindex will return a "Substring not found" ValueError in that case.

2023-03-22 14:30 UTC, dbb-aws-only submitted a review, later dismissed
As long as we're ok with not trapping a ValueError in the rindex on lines 16 and 23 - this code looks great

2023-03-22 14:58 UTC, bassemwanis commented on source/refreezer/application/chunking/trim.py
> +        chunk = chunk[chunk.rindex(b"\n", 0, max_record_size) + 1 :]
Right, I was thinking that the chunk size should always be greater than the `max_record_size` and should have at least one `\n`. Also since a `ValueError` will be raised, can the callee logic handle it!

2023-03-22 18:31 UTC, kamyarz-aws commented on source/refreezer/application/chunking/trim.py
> +        chunk = chunk[chunk.rindex(b"\n", 0, max_record_size) + 1 :]
docstring best practice is to use it to explain what a function does. In this case the best practice is to simply use multiple lines of comments.
<img width="713" alt="image" src="https://user-images.githubusercontent.com/120507168/227002976-466b1983-a734-4e51-a6bf-840031300dfa.png">

2023-03-22 19:27 UTC, bassemwanis commented on source/tests/unit/application/chunking/test_trim_inventory_chunk.py
> +    assert expected_result == result
Done!

2023-03-22 19:27 UTC, bassemwanis commented on source/refreezer/application/chunking/trim.py
> +        chunk = chunk[chunk.rindex(b"\n", 0, max_record_size) + 1 :]
Done!

2023-03-23 15:27 UTC, dbb-aws-only submitted a review, later dismissed

2023-03-23 21:17 UTC, kamyarz-aws submitted a review, later dismissed

2023-03-23 21:56 UTC, schana requested changes

2023-03-23 21:56 UTC, schana commented on source/refreezer/application/chunking/trim.py
> +        chunk = chunk[chunk.rindex(b"\n", 0, max_record_size) + 1 :]
We should add edge-case testing for what happens when the newline ends up on the boundaries of the max_record_size as well as chunks.

2023-03-24 20:34 UTC, bassemwanis commented on source/refreezer/application/chunking/trim.py
> +        chunk = chunk[chunk.rindex(b"\n", 0, max_record_size) + 1 :]
Done! Also I have added a new test to chunk an input byte array, trim each chunk, and then reassemble the chunks back into a single byte array.

2023-03-26 12:03 UTC, dbb-aws-only approved these changes
The testing for this code is excellent - I love the corner cases that you've covered.  I think it's ready to merge now.

2023-03-27 17:29 UTC, dbb-aws-only commented on source/refreezer/application/chunking/trim.py
> +        chunk = chunk[chunk.rindex(b"\n", 0, max_record_size) :]
I know this doesn't belong in a code review, but the Robot Smile  `:]` makes me happy.

2023-03-27 20:04 UTC, simonkrol approved these changes

2023-03-27 21:25 UTC, schana approved these changes

2023-03-27 23:41 UTC, merged